In [1]:
from sklearn import datasets
iris = datasets.load_iris()

print(iris)
type(iris)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

sklearn.utils._bunch.Bunch

In [13]:
x = iris.data 
y = iris.target 

print(x[:6])

print(y[:6])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]]
[0 0 0 0 0 0]


In [15]:
import numpy as np
data = np.column_stack((x,y))
print(data)

[[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]
 [5.4 3.9 1.7 0.4 0. ]
 [4.6 3.4 1.4 0.3 0. ]
 [5.  3.4 1.5 0.2 0. ]
 [4.4 2.9 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.4 3.7 1.5 0.2 0. ]
 [4.8 3.4 1.6 0.2 0. ]
 [4.8 3.  1.4 0.1 0. ]
 [4.3 3.  1.1 0.1 0. ]
 [5.8 4.  1.2 0.2 0. ]
 [5.7 4.4 1.5 0.4 0. ]
 [5.4 3.9 1.3 0.4 0. ]
 [5.1 3.5 1.4 0.3 0. ]
 [5.7 3.8 1.7 0.3 0. ]
 [5.1 3.8 1.5 0.3 0. ]
 [5.4 3.4 1.7 0.2 0. ]
 [5.1 3.7 1.5 0.4 0. ]
 [4.6 3.6 1.  0.2 0. ]
 [5.1 3.3 1.7 0.5 0. ]
 [4.8 3.4 1.9 0.2 0. ]
 [5.  3.  1.6 0.2 0. ]
 [5.  3.4 1.6 0.4 0. ]
 [5.2 3.5 1.5 0.2 0. ]
 [5.2 3.4 1.4 0.2 0. ]
 [4.7 3.2 1.6 0.2 0. ]
 [4.8 3.1 1.6 0.2 0. ]
 [5.4 3.4 1.5 0.4 0. ]
 [5.2 4.1 1.5 0.1 0. ]
 [5.5 4.2 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.2 0. ]
 [5.  3.2 1.2 0.2 0. ]
 [5.5 3.5 1.3 0.2 0. ]
 [4.9 3.6 1.4 0.1 0. ]
 [4.4 3.  1.3 0.2 0. ]
 [5.1 3.4 1.5 0.2 0. ]
 [5.  3.5 1.3 0.3 0. ]
 [4.5 2.3 1.3 0.3 0. ]
 [4.4 3.2 1.3 0.2 0. ]
 [5.  3.5 1

In [17]:
import pandas as pd
df = pd.DataFrame(data)

print(df)

       0    1    2    3    4
0    5.1  3.5  1.4  0.2  0.0
1    4.9  3.0  1.4  0.2  0.0
2    4.7  3.2  1.3  0.2  0.0
3    4.6  3.1  1.5  0.2  0.0
4    5.0  3.6  1.4  0.2  0.0
..   ...  ...  ...  ...  ...
145  6.7  3.0  5.2  2.3  2.0
146  6.3  2.5  5.0  1.9  2.0
147  6.5  3.0  5.2  2.0  2.0
148  6.2  3.4  5.4  2.3  2.0
149  5.9  3.0  5.1  1.8  2.0

[150 rows x 5 columns]


In [19]:
df.columns = ["opal length", "opal width", "petal length", "petal width", "class"]
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   opal length   150 non-null    float64
 1   opal width    150 non-null    float64
 2   petal length  150 non-null    float64
 3   petal width   150 non-null    float64
 4   class         150 non-null    float64
dtypes: float64(5)
memory usage: 6.0 KB


In [20]:
df["class"] = df["class"].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   opal length   150 non-null    float64
 1   opal width    150 non-null    float64
 2   petal length  150 non-null    float64
 3   petal width   150 non-null    float64
 4   class         150 non-null    int64  
dtypes: float64(4), int64(1)
memory usage: 6.0 KB


In [21]:
df.describe()

opal length  opal width  petal length  petal width       class
count   150.000000  150.000000    150.000000   150.000000  150.000000
mean      5.843333    3.057333      3.758000     1.199333    1.000000
std       0.828066    0.435866      1.765298     0.762238    0.819232
min       4.300000    2.000000      1.000000     0.100000    0.000000
25%       5.100000    2.800000      1.600000     0.300000    0.000000
50%       5.800000    3.000000      4.350000     1.300000    1.000000
75%       6.400000    3.300000      5.100000     1.800000    2.000000
max       7.900000    4.400000      6.900000     2.500000    2.000000

In [22]:
round(df.describe(),2)

opal length  opal width  petal length  petal width   class
count       150.00      150.00        150.00       150.00  150.00
mean          5.84        3.06          3.76         1.20    1.00
std           0.83        0.44          1.77         0.76    0.82
min           4.30        2.00          1.00         0.10    0.00
25%           5.10        2.80          1.60         0.30    0.00
50%           5.80        3.00          4.35         1.30    1.00
75%           6.40        3.30          5.10         1.80    2.00
max           7.90        4.40          6.90         2.50    2.00

In [23]:
df.loc[4] #locacion en torno al indice

opal length     5.0
opal width      3.6
petal length    1.4
petal width     0.2
class           0.0
Name: 4, dtype: float64

In [ ]:
df.loc[]

In [24]:
df.iloc[:,:]

opal length  opal width  petal length  petal width  class
0            5.1         3.5           1.4          0.2      0
1            4.9         3.0           1.4          0.2      0
2            4.7         3.2           1.3          0.2      0
3            4.6         3.1           1.5          0.2      0
4            5.0         3.6           1.4          0.2      0
..           ...         ...           ...          ...    ...
145          6.7         3.0           5.2          2.3      2
146          6.3         2.5           5.0          1.9      2
147          6.5         3.0           5.2          2.0      2
148          6.2         3.4           5.4          2.3      2
149          5.9         3.0           5.1          1.8      2

[150 rows x 5 columns]